name: Daily Build

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  spec:
    name: crystal ${{ matrix.crystal }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]

    steps:
      - uses: actions/checkout@v4

      - uses: crystal-lang/install-crystal@v1
        id: install_crystal
        with:
          crystal: ${{ matrix.crystal }}

      - name: Crystal and Shards versions
        run: |
          crystal version
          shards --version

      - name: Install dependencies
        run: shards install

      - name: Run specs
        run: crystal spec
